Repository nathanhoad/godot_dialogue_manager, pull requests merged in 2025-03, with the labels that each got.

#809 Subtly highlight character names
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
Labels: enhancement

#814 Fix import & using syntax highlighting
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
  addons/dialogue_manager/constants.gd
Labels: bug

#815 Trim dialogue editor from exported builds
  Dialogue Manager.csproj
  addons/dialogue_manager/export_plugin.gd
  addons/dialogue_manager/export_plugin.gd.uid
  addons/dialogue_manager/plugin.gd
Labels: enhancement

#817 Fix Typo in 2to3.md
  docs/2to3.md
Labels: documentation

#819 Moving add and remove autoload to enable and disable plugin functions
  addons/dialogue_manager/plugin.gd
Labels: enhancement

#820 Set Id in DialogueLine
  addons/dialogue_manager/DialogueManager.cs
Labels: bug

#824 Fix imported titles that are indented
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
Labels: bug

#825 Add null coalescing
  addons/dialogue_manager/compiler/compiler_regex.gd
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
  addons/dialogue_manager/constants.gd
  addons/dialogue_manager/dialogue_manager.gd
  docs/Conditions_Mutations.md
  tests/state_for_tests.gd
  tests/test_state.gd
Labels: enhancement

#826 Add missing export plugin name
  addons/dialogue_manager/export_plugin.gd
Labels: bug

#837 Remember scroll position for edited files
  addons/dialogue_manager/settings.gd
  addons/dialogue_manager/views/main_view.gd
Labels: enhancement

#838 Fix find and replace index reset
  addons/dialogue_manager/components/find_in_files.gd
  addons/dialogue_manager/components/search_and_replace.gd
Labels: bug

#839 Restore missing exported internal translations
  addons/dialogue_manager/export_plugin.gd
Labels: bug

#840 Fix expression jumps only evaluating once
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#841 Ensure state has script before checking script
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug
