Repository nathanhoad/godot_dialogue_manager, pull requests merged in 2025-01, with the labels that each got.

#714 Fixes issue where multiple recursive goto lines don't reset the label text
  addons/dialogue_manager/dialogue_label.gd
Labels: bug

#716 Give example balloon copies a new UID
  addons/dialogue_manager/plugin.gd
Labels: enhancement

#718 Ensure example balloon copy has a unique UID
  addons/dialogue_manager/plugin.gd
Labels: enhancement

#725 Fix newlines breaking key generation
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#726 Defer adding balloon to scene
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/example_balloon/ExampleBalloon.cs
  addons/dialogue_manager/example_balloon/example_balloon.gd
Labels: bug

#729 Allow special quotes in translated replacements
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#731 Added CreateResourceFromString to the c# wrapper
  addons/dialogue_manager/DialogueManager.cs
  docs/CSharp.md
Labels: enhancement

#730 Delay reimporting to avoid clashes with editor
  addons/dialogue_manager/components/dialogue_cache.gd
  addons/dialogue_manager/plugin.gd
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#733 Fix responses menu keyboard input
  addons/dialogue_manager/dialogue_reponses_menu.gd
  addons/dialogue_manager/plugin.gd
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#734 Added signal to DialogueManager for when dialogue starts
  addons/dialogue_manager/dialogue_manager.gd
  docs/API.md
Labels: enhancement

#737 Fix importing when blank
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/resolved_goto_data.gd
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/plugin.gd
  tests/state_for_tests.gd
  tests/test_jumps.gd
Labels: bug

#743 Fix "else" being incorrectly required
  addons/dialogue_manager/compiler/compiled_line.gd
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_state.gd
Labels: bug

#744 Fix title not found if after dedent
  addons/dialogue_manager/compiler/compilation.gd
  tests/test_basic_dialogue.gd
Labels: bug

#748 Fix newline literals being ignored
  addons/dialogue_manager/compiler/compilation.gd
Labels: bug

#749 Restore [next] documentation
  docs/Basic_Dialogue.md
Labels: documentation

#750 Fix empty lines breaking response grouping
  addons/dialogue_manager/compiler/compilation.gd
  tests/test_responses.gd
Labels: bug

#751 Keep previous get_current_scene data in C# bridge
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#756 Fix issue with if grouping with wrong else
  addons/dialogue_manager/compiler/compilation.gd
  tests/test_state.gd
Labels: bug

#757 Fix nestled inline mutations being clobbered
  addons/dialogue_manager/dialogue_label.gd
  addons/dialogue_manager/utilities/builtins.gd
  tests/test_dialogue_label.gd
Labels: bug

#758 Fix conditional responses with static IDs
  addons/dialogue_manager/compiler/compilation.gd
  tests/test_basic_dialogue.gd
  tests/test_responses.gd
Labels: bug

#760 Add a check for top-level state name collisions
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/l10n/en.po
  addons/dialogue_manager/l10n/translations.pot
  addons/dialogue_manager/settings.gd
  docs/Settings.md
  tests/test_state.gd
Labels: enhancement
