Repository nathanhoad/godot_dialogue_manager, pull requests merged in 2025-04, with the labels that each got.

#846 Find in files now centers on clicked search result
  addons/dialogue_manager/views/main_view.gd
Labels: enhancement

#847 Fix line ID highlighting when there's no character
  Dialogue Manager.csproj
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
Labels: bug

#857 Fix setting for missing translation warning
  addons/dialogue_manager/compiler/compilation.gd
Labels: bug

#858 Fix highlighting when no character but yes ID
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
Labels: bug

#859 Fix inline comment syntax highlighting
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
Labels: bug

#861 Improve nested dialogue compile warnings
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/tree_line.gd
  addons/dialogue_manager/constants.gd
  addons/dialogue_manager/l10n/en.po
  addons/dialogue_manager/l10n/translations.pot
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#866 Fix responses if children of condition
  addons/dialogue_manager/compiler/compilation.gd
Labels: bug

#864 Remove duplicate line from Translations docs
  docs/Translations.md
Labels: documentation

#867 Stop invalidating resources with errors
  addons/dialogue_manager/import_plugin.gd
Labels: enhancement

#868 Add methods for finding lines by their static IDs
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_basic_dialogue.gd
Labels: enhancement

#871 Better handle nested dialogue errors
  addons/dialogue_manager/compiler/compilation.gd
  tests/test_basic_dialogue.gd
Labels: enhancement

#872 Add basic auto complete for mutation lines
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/components/code_edit.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
  addons/dialogue_manager/dialogue_manager.gd
Labels: enhancement

#873 Add condition_as_text to DialogueResponses
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/compiled_line.gd
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/dialogue_response.gd
  tests/test_responses.gd
Labels: enhancement

#874 Fix issue with optional C# mutation parameters
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/components/code_edit.gd
Labels: bug

#875 Update API docs
  docs/API.md
Labels: documentation

#877 Add wider support for basic auto-complete
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/components/code_edit.gd
Labels: enhancement

#878 Add setting for extra auto-complete sources
  addons/dialogue_manager/components/code_edit.gd
  addons/dialogue_manager/settings.gd
  docs/Settings.md
Labels: enhancement

#881 Allow multiple values in when clauses
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_state.gd
Labels: enhancement

#880 Fix search not updating on file change
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#885 Fix custom test scene failing to run from UID
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#886 Add left and right response menu navigation
  addons/dialogue_manager/dialogue_responses_menu.gd
Labels: enhancement
