Repository nathanhoad/godot_dialogue_manager, pull requests merged in 2025-07, with the labels that each got.

#922 Add started_typing signal to DialogueLabel
  addons/dialogue_manager/dialogue_label.gd
  docs/API.md
  docs/Using_Dialogue.md
Labels: enhancement

#933 Allow overriding dialogue label text setter
  addons/dialogue_manager/dialogue_label.gd
Labels: enhancement

#945 Fix incorrectly failing match cases
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_state.gd
Labels: bug

#940 Add GetLine to C#
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/dialogue_manager.gd
Labels: enhancement

#943 Make dialogue label use _update_text() when setting text in type_out()
  addons/dialogue_manager/dialogue_label.gd
Labels: bug

#939 Add MutationBehavior passthrough to C# get_next_dialogue_line bridge
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/dialogue_manager.gd
Labels: enhancement

#941 Update Extra game state docs
  docs/Conditions_Mutations.md
Labels: documentation
