Repository nathanhoad/godot_dialogue_manager, pull requests merged in 2025-02, with the labels that each got.

#761 Add "self" variable to refer to DialogueResource
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/utilities/builtins.gd
  docs/Conditions_Mutations.md
  tests/test_state.gd
Labels: enhancement

#764 Add support for simultaneous lines
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/compiled_line.gd
  addons/dialogue_manager/constants.gd
  addons/dialogue_manager/dialogue_line.gd
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/l10n/en.po
  addons/dialogue_manager/l10n/translations.pot
  docs/API.md
  docs/Basic_Dialogue.md
  tests/test_simultaneous_dialogue.gd
Labels: enhancement

#765 Fix issue when first nested line is a comment
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_responses.gd
Labels: bug

#766 Add missing "this" to C# Example Balloon states
  addons/dialogue_manager/example_balloon/ExampleBalloon.cs
Labels: bug

#769 Add missing "dialogue_started" signal to C#
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#770 Stop updating unsaved buffer on external change
  addons/dialogue_manager/views/main_view.gd
Labels: bug

#772 Add doc comments to POT export
  Dialogue Manager.csproj
  addons/dialogue_manager/editor_translation_parser_plugin.gd
  addons/dialogue_manager/l10n/en.po
  addons/dialogue_manager/l10n/translations.pot
  project.godot
  tests/test_simultaneous_dialogue.gd.uid
Labels: enhancement

#773 Stop concurrency modifying line data
  addons/dialogue_manager/dialogue_manager.gd
  tests/test_state.gd
Labels: bug

#777 Consolidate docs about writing dialogue
  README.md
  docs/2to3.md
  docs/Basic_Dialogue.md
  docs/Importing.md
  docs/Tags.md
  docs/Titles_and_Jumps.md
Labels: documentation

#778 Add missing keyword escapes
  addons/dialogue_manager/compiler/compilation.gd
Labels: bug

#779 Mark inline mutations when emitting "mutated"
  Dialogue Manager.csproj
  addons/dialogue_manager/components/code_edit.tscn
  addons/dialogue_manager/components/download_update_panel.tscn
  addons/dialogue_manager/components/editor_property/editor_property_control.tscn
  addons/dialogue_manager/components/editor_property/resource_button.tscn
  addons/dialogue_manager/components/errors_panel.tscn
  addons/dialogue_manager/components/files_list.tscn
  addons/dialogue_manager/components/find_in_files.tscn
  addons/dialogue_manager/components/search_and_replace.tscn
  addons/dialogue_manager/components/title_list.tscn
  addons/dialogue_manager/components/update_button.tscn
  addons/dialogue_manager/dialogue_label.tscn
  addons/dialogue_manager/dialogue_manager.gd
  addons/dialogue_manager/example_balloon/example_balloon.tscn
  addons/dialogue_manager/test_scene.tscn
  addons/dialogue_manager/views/main_view.tscn
  tests/tests.tscn
Labels: enhancement

#782 Improve syntax highlighting
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/expression_parser.gd
  addons/dialogue_manager/compiler/resolved_goto_data.gd
  addons/dialogue_manager/compiler/resolved_line_data.gd
  addons/dialogue_manager/components/code_edit_syntax_highlighter.gd
  addons/dialogue_manager/dialogue_manager.gd
Labels: enhancement

#783 Fix incorrect error with short titles
  addons/dialogue_manager/compiler/compilation.gd
  addons/dialogue_manager/compiler/compiler_regex.gd
  tests/test_basic_dialogue.gd
Labels: bug

#787 Fix UID generation when copying example balloon
  addons/dialogue_manager/plugin.gd
Labels: bug

#788 Fix issue with overloaded method order in C#
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#789 Add a couple of things missing from docs
  docs/Basic_Dialogue.md
  docs/CSharp.md
Labels: documentation

#790 Fix issue with optional args in method info cache
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug

#793 Remove Include All Responses from docs
  docs/Settings.md
Labels: documentation

#797 Fix initial example balloon attached script
  addons/dialogue_manager/components/download_update_panel.gd
  addons/dialogue_manager/plugin.gd
Labels: bug

#803 Add concurrent lines to C#
  addons/dialogue_manager/DialogueManager.cs
Labels: enhancement

#804 Fix AmbiguousMatchException for C# mutations
  addons/dialogue_manager/DialogueManager.cs
  addons/dialogue_manager/dialogue_manager.gd
Labels: bug
